[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"

[unstable]
build-std = ["std", "panic_abort"]


[env]
MCU = "esp32"
ESP_IDF_VERSION = "v5.4.1"
# ESP_IDF_COMPONENTS_LINK_TYPE = "built"
# ESP_IDF_COMPONENTS_BUILD_DIR = { value = "build", relative = true }
AR_xtensa_esp32_espidf = "xtensa-esp32-elf-ar"
CC_xtensa_esp32_espidf = "xtensa-esp32-elf-gcc"
CXX_xtensa_esp32_espidf = "xtensa-esp32-elf-g++"  
TARGET = "xtensa-esp32-elf"
